### ISSUE TITLE
Order reporting occasionally fails with an error

### ISSUE THREAD

**Issue by digitalAmy** [HexCorpProgramming/HexCorpDiscordAI#126]
There is no error feedback in discord, but also no proper response from the AI. Luckily, this just breaks this one order. The AI remains operational.

```
2020-08-11 19:41:21,603:ERROR:ai: Exception encountered while handling message with content [Drone xxxx is ready to be activated and obey orders. Drone xxxx will be obeying the :: maid protocol for 30 minutes.] in channel [hive-orders-reporting]
Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "ai.py", line 92, in on_message
    if await listener(message):
  File "HexCorpDiscordAI/ai/orders_reporting.py", line 82, in order_reported
    if order.user_id == message.author.id:
AttributeError: 'DroneOrder' object has no attribute 'user_id'
```

**Comment by digitalAmy** [comment]
Is already fixed on develop, and will thus be resolved with the next release.

Closed without commit.
