### ISSUE TITLE
amplification with a non-existent drone creates an error

### ISSUE THREAD

**Issue by digitalAmy** [HexCorpProgramming/HexCorpDiscordAI#135]
```
DEBUG:ai:Preparing drone XXXX for amplification.
ERROR:ai:!!! Exception caught in amplify command !!!
INFO:ai:Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "f:/Projekte/HexCorpDiscordAI/ai.py", line 95, in amplify
    for amp_profile in amplifier.generate_amplification_information(target_channel, drones):
  File "f:/Projekte/HexCorpDiscordAI\ai\amplifier.py", line 21, in generate_amplification_information
    amplification_avatar = amplifier_drone.avatar_url
AttributeError: 'NoneType' object has no attribute 'avatar_url'
```

**Comment by digitalAmy** [comment]
I have no clue how this could have happened. Going to close this for now, as it does not really break anything.
