### ISSUE TITLE
Battery draining throws exception

### ISSUE THREAD

**Issue by digitalAmy** [HexCorpProgramming/HexCorpDiscordAI#339]
on the first tick of draining drones this happened

```
INFO:ai:Draining 1 minute worth of charge from 9813
Unhandled exception in internal background task 'track_active_battery_drain'.
Traceback (most recent call last):
  File "/root/hexcorp-mxtress-ai/HexCorpDiscordAI/env/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 176, in _loop
    await self.coro(*args, **kwargs)
  File "/root/hexcorp-mxtress-ai/HexCorpDiscordAI/ai/battery.py", line 73, in track_active_battery_drain
    deincrement_battery_minutes_remaining(drone_id=drone)
  File "/root/hexcorp-mxtress-ai/HexCorpDiscordAI/db/drone_dao.py", line 149, in deincrement_battery_minutes_remaining
    change('UPDATE drone SET battery_minutes = :minutes WHERE drone_id = :drone_id', {'minutes': drone_record['battery_minutes'] - 1, 'drone_id': drone_id})
TypeError: 'NoneType' object is not subscriptable
INFO:ai:Checking for drones with drained battery.
```

**Comment by digitalAmy** [comment]
I could not reproduce this and it seems to not appear in the logs anymore for now. I will keep an eye on it for a bit longer to see if it pops up agian.
