### ISSUE TITLE
While glitch role is enabled, images do not glitch.

### ISSUE THREAD

**Issue by primis** [HexCorpProgramming/HexCorpDiscordAI#478]
Images do not become glitched, but also the text in any post with images does not glitch either
![image](https://github.com/user-attachments/assets/71a568e3-ad1c-4198-ae39-300037d9387f)

**Comment by 3287** [comment]
Images are still not being glitched with the config enabled, no matter if the filetype is supported or not. When testing with a `.jpg` file:

```
2024-11-16 :: 14:34:26.981 :: INFO :: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/glitch_this/glitch_this.py", line 191, in glitch_image
    img = self.fetch_image(src_img, gif_allowed=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/glitch_this/glitch_this.py", line 107, in fetch_image
    raise Exception('Wrong format')
Exception: Wrong format

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 400, in _run_event
    await coro(args, **kwargs)
  File "/var/opt/HexCorpDiscordAI/main.py", line 252, in wrapper
    await func(message)
  File "/var/opt/HexCorpDiscordAI/src/db/database.py", line 69, in runner
    return await create_task(run_with_connection(args, kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/opt/HexCorpDiscordAI/src/db/database.py", line 65, in run_with_connection
    return await func(args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/opt/HexCorpDiscordAI/main.py", line 283, in on_message
    if await listener(message, message_copy):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/opt/HexCorpDiscordAI/src/ai/glitch_message.py", line 143, in glitch_if_applicable
    message_copy.attachments = await glitch_images(message.attachments, glitch_amount)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/opt/HexCorpDiscordAI/src/ai/glitch_message.py", line 109, in glitch_images
    glitched_pillow = glitcher.glitch_image(pillow, max(0.1, glitch_amount / 10))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/glitch_this/glitch_this.py", line 197, in glitch_image
    raise Exception(
Exception: File format not supported - must be a non-animated image file
```

**Comment by ZebraNorth** [comment]
Can't reproduce this, even tried downloading and reuploading the image that @3287 tested and it was glitched by the bot.

**Comment by ZebraNorth** [comment]
Reproduced it, it only happens when there is no text sent along with the image.  Probably the message handler is not being called.
